"""initial schema

Revision ID: b95de33ef9b0
Revises: 
Create Date: 2026-05-21 21:20:46.440374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95de33ef9b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'clinician', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('pain_type', sa.String(length=200), nullable=False),
    sa.Column('pain_level_baseline', sa.Integer(), nullable=False),
    sa.Column('treatment_context', sa.Text(), nullable=False),
    sa.Column('tone_preference', sa.Enum('direct_informative', 'balanced', 'supportive_sustaining', name='tone_preference_enum'), nullable=False),
    sa.Column('voice_preference', sa.Enum('alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer', name='voice_preference_enum'), nullable=False),
    sa.Column('communication_style', sa.Text(), nullable=False),
    sa.Column('current_valence_dial', sa.Float(), nullable=False),
    sa.Column('current_intervention_type', sa.Enum('cognitive_reframing', 'interoceptive_attention', name='intervention_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ritual_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'generating', 'ready', 'in_progress', 'completed', 'skipped', 'failed', name='session_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.Enum('before', 'during', 'after', name='session_phase_enum'), nullable=True),
    sa.Column('script_before', sa.Text(), nullable=True),
    sa.Column('script_during', sa.Text(), nullable=True),
    sa.Column('script_after', sa.Text(), nullable=True),
    sa.Column('audio_before_path', sa.String(), nullable=True),
    sa.Column('audio_during_path', sa.String(), nullable=True),
    sa.Column('audio_after_path', sa.String(), nullable=True),
    sa.Column('intervention_type', sa.Enum('cognitive_reframing', 'interoceptive_attention', name='intervention_type_session_enum'), nullable=False),
    sa.Column('valence_dial', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adaptation_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('old_valence', sa.Float(), nullable=False),
    sa.Column('new_valence', sa.Float(), nullable=False),
    sa.Column('old_intervention_type', sa.Enum('cognitive_reframing', 'interoceptive_attention', name='intervention_type_adapt_enum'), nullable=False),
    sa.Column('new_intervention_type', sa.Enum('cognitive_reframing', 'interoceptive_attention', name='intervention_type_adapt_new_enum'), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ritual_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('phase', sa.Enum('before', 'during', 'after', 'overall', name='feedback_phase_enum'), nullable=False),
    sa.Column('in_session_rating', sa.Enum('helping', 'neutral', 'not_helping', name='in_session_rating_enum'), nullable=True),
    sa.Column('post_pain_level', sa.Integer(), nullable=True),
    sa.Column('post_session_notes', sa.Text(), nullable=True),
    sa.Column('perceived_benefit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ritual_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_feedback')
    op.drop_table('adaptation_log')
    op.drop_table('ritual_sessions')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
